# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='daily_bizz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_station', models.IntegerField()),
                ('flash_mem', models.IntegerField()),
                ('comp_repair', models.IntegerField()),
                ('date_time', models.DateField()),
            ],
        ),
    ]
