# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_bizz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_bizz',
            name='comp_repair',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='daily_bizz',
            name='flash_mem',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='daily_bizz',
            name='play_station',
            field=models.IntegerField(default=0),
        ),
    ]
