# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_bizz', '0002_auto_20160506_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='electricity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_reading', models.CharField(max_length=10)),
                ('weelky_reading', models.CharField(max_length=10)),
                ('amt_deposited', models.IntegerField(default=0)),
                ('date_time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='hard_ware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('installation_amt', models.IntegerField(default=0)),
            ],
        ),
    ]
