# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_bizz', '0003_electricity_hard_ware'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricity',
            name='daily_reading',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='electricity',
            name='weelky_reading',
            field=models.FloatField(default=0),
        ),
    ]
