# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 07:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_bizz', '0004_auto_20160512_1018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electricity',
            old_name='weelky_reading',
            new_name='weekly_reading',
        ),
    ]
