# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 07:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auto_bizz', '0005_auto_20160512_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='hard_ware',
            name='date_time',
            field=models.DateField(default=datetime.datetime(2016, 5, 12, 7, 50, 22, 42767, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
