# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_bizz', '0006_hard_ware_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_bizz',
            name='others_amt',
            field=models.IntegerField(default=0),
        ),
    ]
