# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 09:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_bizz', '0007_daily_bizz_others_amt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daily_bizz',
            name='others_amt',
        ),
    ]
